# Generated by Django 5.1.1 on 2024-09-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='nf',
        ),
    ]
