# Generated by Django 5.1.1 on 2024-09-24 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_remove_doctor_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('DO', 'DO'), ('DNB', 'DNB'), ('MS', 'MS'), ('BDS', 'BDS'), ('MDS', 'MDS'), ('PhD', 'PhD'), ('MPH', 'MPH'), ('DM', 'DM'), ('MCh', 'MCh'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS'), ('BPT', 'BPT'), ('MPT', 'MPT'), ('BVSc', 'BVSc'), ('MSc', 'MSc'), ('DGO', 'DGO'), ('FRCS', 'FRCS'), ('MRCP', 'MRCP'), ('DCH', 'DCH'), ('DPH', 'DPH'), ('DDS', 'DDS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
